"$schema" = 'https://starship.rs/config-schema.json'

# Disable the giant newline at the start of the prompt
add_newline = true

# Custom plain format
format = """$directory$git_branch$git_status$character"""

[directory]
style = "bold blue"
truncation_length = 3
truncation_symbol = ".../"

[character]
success_symbol = "[->](bold green)"
error_symbol = "[x](bold red)"

[git_branch]
symbol = "git:"
style = "bold purple"

[git_status]
format = "([\\[$all_status$ahead_behind\\]]($style) )"
style = "red"

# Kill all the language/container waffle
[package]
disabled = true
[docker_context]
disabled = true
[fortran]
disabled = true
[lua]
disabled = true
[nodejs]
disabled = true
[python]
disabled = true
